# Generated by Django 3.0.4 on 2020-03-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Surname', models.CharField(max_length=30)),
                ('Secondname', models.CharField(max_length=30)),
                ('Rank', models.CharField(max_length=30)),
                ('Tel', models.CharField(max_length=30)),
                ('Ip_tel', models.CharField(max_length=30)),
            ],
        ),
    ]
